### ISSUE TITLE
postprocessing issue

### ISSUE THREAD

**Issue by dpdclub** [phydev/angio#4]
Dear Maurício, 

We run into some issue when postprocessing the results, after remove all the space within the file name, we  tried to run run_get, but it awlays gave us error as follows,  do you have a clue of why this is happening,

Thanks a lot,

```{bash}
:~/Desktop/tumor/angio-master$ ./run_get
 initial file, last_file, delta, dir_name:
10, 50 ,10, 001 
 ---------------------------------------------------------
                       get_data_m module

  This program calculate the mean diameter and the
  the number of branches for each time step of a
  simulation and plot two graphs as a function of time.
 ---------------------------------------------------------
Calculating . . .
          10
wc: 001/phi: No such file or directory
wc: 10.xyz: No such file or directory
wc: 001/phis: No such file or directory
wc: 10.xyz: No such file or directory
          20
wc: 001/phi: No such file or directory
wc: 20.xyz: No such file or directory
wc: 001/phis: No such file or directory
wc: 20.xyz: No such file or directory
          30
wc: 001/phi: No such file or directory
wc: 30.xyz: No such file or directory
wc: 001/phis: No such file or directory
wc: 30.xyz: No such file or directory
          40
wc: 001/phi: No such file or directory
wc: 40.xyz: No such file or directory
wc: 001/phis: No such file or directory
wc: 40.xyz: No such file or directory
          50
wc: 001/phi: No such file or directory
wc: 50.xyz: No such file or directory
wc: 001/phis: No such file or directory
wc: 50.xyz: No such file or directory
At line 121 of file run_get.F90 (unit = 16, file = 'plot_file.aux')
Fortran runtime error: Cannot write to file opened for READ
```

**Comment by phydev** [comment]
Hi,

The error says that the program cannot find your files in the specified location. You're probably running the script in the wrong folder.

Check out the path where the data is expected to be, relative to the script location in the source code: 

https://github.com/phydev/angio/blob/c4b3988ca5f2e3c2bdc7ea6d892f68d271028bc1/tools/run_get.F90#L63

**Comment by dpdclub** [comment]
Hi Maurício,

Thanks for your reply.  Another question is how do you visualize the results and make a plot like what you have shown in the front page of this github page.

Thanks,

**Comment by phydev** [comment]
I suggest you to use [VisIt](https://visit-dav.github.io/visit-website/) or [Paraview](https://www.paraview.org) to make 3D visualisations. In my opinion VisIt is the best, but I know some people prefer Paraview. :)

I have a script to convert XYZ to VTI format:

https://github.com/phydev/scripts/blob/master/xyz2vti.py

**Comment by dpdclub** [comment]
Thanks for providing this information.  Could you also please help me to clarify what are stored in phi.xyz, phis.xyz, t.xyz and ti.xyz, respectively.

**Comment by phydev** [comment]
If I remember correctly, these files are generated in the last step of the simulation. All of them are organised with the CSV format and have four columns with the spatial coordinates $(x,y,z)$ and a fourth column with different fields. The files with suffix `i` identify the initial condition. Numbered files are snapshots of the system in transient states along the simulation, the numbers are time steps. 

- `phi.xyz` contains the field $\phi \in [-1, 1]$ in its fourth column, which represents the vessels;
- `phis.xyz` contains the data for the field $\psi$ that represents the VEGF sources;
- `t.xyz` contains the VEGF concentration $T$.

See Fig. 1 of the [paper](https://www.nature.com/articles/s41598-018-27034-8):  

![Figure1](https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41598-018-27034-8/MediaObjects/41598_2018_27034_Fig1_HTML.jpg?as=webp)

**Comment by dpdclub** [comment]
Got it.  Thanks for the explaination.  How do you connect the ϕ in phi.xyz with the diameter of the vessels

**Comment by phydev** [comment]
What do you mean? How is the mean diameter computed?  

We have the total volume occupied by the vessels (all points where $phi$>0), the number of vessels, and the length of the vessels, all obtained from the thinning algorithm. You can define the total volume occupied by the number of vessels to obtain the mean vessel volume. If you assume that the vessels are cylindrical you can  use basic geometry to obtain the diameter:
https://github.com/phydev/angio/blob/c4b3988ca5f2e3c2bdc7ea6d892f68d271028bc1/tools/run_get.F90#L111 

We cleaned up the data by removing volume relative to very short vessels (we named it `dead_volume`): 
https://github.com/phydev/angio/blob/c4b3988ca5f2e3c2bdc7ea6d892f68d271028bc1/tools/get_data_m.F90#L374

**Comment by dpdclub** [comment]
I mean the way to assess the diameter of new vessels at different locations like ϕ .  The reason I am asking is that I want to run simulate the blood flow and how the red blood cells are transporting within this newly generated vessels.  Or It would be easier if I can extract the boundary of the newly generated new vessels from the results so I can perfuse blood within these vessels using my solver,   please let me know if this is doable.  

Thanks,

**Comment by phydev** [comment]
You can extract the boundaries, since it is well defined by the region of phase transition between the interior and the exterior of the vessels. However, modelling red blood cells is costly due to the computation of the Canham-Helfrich functional to model the membrane. Integrating everything at the same time can be challenging because of different time scales across the membrane relaxation, the blood vessels growth, and the advection. Maybe a sharp interface model for the vessels could work better? I'm not sure, but it's certainly an interesting problem. 

I recently left academia, but the last master student I co-supervised modelled red blood cells, so it can useful to look up his thesis or other published works from the main supervisor lab (his thesis will be available online soon.)

The PI, my former PhD supervisor, is always looking forward for new collaborations, so I also recommend to keep in touch with him if you are interested (he is super nice!): 
https://biologicalmodelling.com/

https://scholar.google.pt/citations?hl=en&user=GCWOijAAAAAJ&view_op=list_works&sortby=pubdate

**Comment by dpdclub** [comment]
Great to hear your thoughts and thanks for making the connection.  I plan to extract the boundary and simulate blood flow using an different solver, not the phase-field.  With the current postpreocess tools you provided, could we extract the boundary from the phi.xyz files?  Also, in the input, how do we specify which rule of deactivating the hypoxic cells will be used, like the rule 1 and 2 introduced in the paper.  Also how to specify the initial number of the hypoxic cells or the number of VEGF sources in the simulation system.

Thanks,

**Comment by phydev** [comment]
_With the current postprocess tools you provided, could we extract the boundary from the phi.xyz files?_

No, I haven't implemented that feature. VisIt and Paraview can identify and render the boundaries automatically, if you need it for subsequent computations you will need to implement yourself according to the method you will use to model the red blood cells. 

_Also, in the input, how do we specify which rule of deactivating the hypoxic cells will be used, like the rule 1 and 2 introduced in the paper. Also how to specify the initial number of the hypoxic cells or the number of VEGF sources in the simulation system._

That is documented in the [README.md](https://github.com/phydev/angio/blob/master/README.md). The variable `flow_FT` (boolean) activate and deactivate the blood flow computation. If activated, the VEGF production is regulated by the presence of blood flow. 

Change `source_max` to specify the maximum number of VEGF sources in the system, we don't set the exact final number because the cells are placed randomly in the box. You can modify the code to add the cells in an ordered manner though, if that is important.

**Comment by dpdclub** [comment]
Hi Maurício,

Thank you very much for these clarifications. One more question on the periodicity,  if I turn on the flag periodic_FT, it means the simulation box is periodic in all the x y z direction or only on the z direction? I see the code comments that if Periodic, it becomes ndim =2, does it mean that there will be no spacial variation along the z direction like the 2D example in the paper？  What happens if Periodic flag is off and the new vessels to the boundary of the simulation box,  do they just stop growing?.

**Comment by phydev** [comment]
I think I implemented reflective boundary conditions in the Z-axis when Periodic is False. This keeps the main vessel in the cilindrical stable solution while avoiding vessels crossing up and down the simulation box. But I think all simulations I ran were with periodic conditions on the 3 directions.

**Comment by dpdclub** [comment]
OK, does it mean that it is always periodic on the x and y direction, there is no switch for that.  Also,  could this code do 2D simulations as the first part of paper shows and what is the flag for it.  Thanks.

**Comment by phydev** [comment]
No, the 2D code was implemented by Rui. The main problem adapting this code to 2D is the thinning algorithm, changing it is not a simple matter of dimensionality reduction - you need to implement a different set of masks for the 2D case.

**Comment by dpdclub** [comment]
Hi Maurício,

I have been running the program and varying the density of the initial source of VEFG to see how the structure of the vessel network changes.  I found that when number of sources are reduced, the initial vessel do not grow out branches, instead they begins to grow themsel in the diameter and become very thick vessels. You the see from the attached images, they even wrap up the VEFG sources.  Do you have any clue of what may cause this?
![3](https://github.com/user-attachments/assets/fedb135d-cf7c-4cd0-8bd3-0051ac0befc8)
![2](https://github.com/user-attachments/assets/0da298d3-25c9-4aba-b771-08c9366b7ff5)
![1](https://github.com/user-attachments/assets/f9fec83a-04b0-4b1c-9c6e-05b01fe19c07)

**Comment by phydev** [comment]
I recommend you to read the paper from 2018 and the previous one from 2011. This is just how the system works, if there is not enough VEGF to activate tip cells then no activation occurs and only proliferation happens in the main vessel. Check out the activation rules we use in the supplementary material or in the code.
